name: Assets check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  assets-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Check assets
        run: python assets_test.py